---
name: Alien-Lightbox
version: 2.03.3.2
author:
  - Graham TerMarsch (cpan@howlingfrog.com)
abstract: installing and finding Lightbox JS
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Alien::scriptaculous: 0
  perl: 5.6.0
build_requires:
  Archive::Zip: 0
  Test::Exception: 0
provides:
  Alien::Lightbox:
    file: lib/Alien/Lightbox.pm
    version: 2.03.3.2
generated_by: Module::Build version 0.2805
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
